parameters:
    bo_shurik_telegram_bot.client.class: BoShurik\TelegramBotBundle\Bot\Client

    bo_shurik_telegram_bot.api.token:
    bo_shurik_telegram_bot.api.tracker_token:

services:
    bo_shurik_telegram_bot.client:
        class: "%bo_shurik_telegram_bot.client.class%"
        arguments:
            - "%bo_shurik_telegram_bot.api.token%"
            - "%bo_shurik_telegram_bot.api.tracker_token%"